# Configuration Options
title: Slide Whistle Project Website
author: "Declan O'Neill and Kip Macsai-Goren"
theme: minima

header-pages:
  - documentation.html
  - resources.html


# Github Pages settings that cannot be changed
# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
